name: Continuous Integration

on:
  push:
    branches: "feature/**"

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root_pass
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - name: Git Checkout
      uses: actions/checkout@v4

    - name: Setup Java SDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Wait for MySQL to be ready
      run: |
        for i in {1..30}; do
          if nc -z localhost 3306; then
            echo "MySQL is up"
            break
          else
            echo "Waiting for MySQL..."
            sleep 2
          fi
        done

    - name: Run Tests
      env:
        SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/testdb
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: root_pass
      run: mvn test

    - name: Build Project
      run: mvn clean package
